# Generated by Django 2.1 on 2020-07-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=11111111111, max_length=11, verbose_name='联系电话'),
            preserve_default=False,
        ),
    ]
