# Generated by Django 2.1 on 2020-05-02 14:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstest',
            name='detail',
            field=tinymce.models.HTMLField(verbose_name='商品详情'),
        ),
        migrations.AlterModelTable(
            name='goodstest',
            table='df_goods_test',
        ),
    ]
