# Generated by Django 2.1 on 2020-05-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_auto_20200504_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atitle', models.CharField(max_length=120)),
                ('aparent', models.ForeignKey(blank=True, null=True, on_delete=None, to='booktest.AreaInfo')),
            ],
        ),
    ]
