# Generated by Django 2.1 on 2020-05-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_areainfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]
