# Generated by Django 2.1 on 2020-05-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20200509_1859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='heroinfo',
            table='heroinfo',
        ),
    ]
